# rustfmt doc - https://rust-lang.github.io/rustfmt/

hard_tabs = false
edition = "2024"

newline_style = "Unix"
indent_style = "Block"

blank_lines_upper_bound = 2

array_width = 80
chain_width = 80
max_width = 120

imports_granularity = "Crate"
reorder_imports = true
group_imports = "StdExternalCrate"
imports_layout = "Vertical"
trailing_comma = "Vertical"

struct_lit_single_line = false
fn_single_line = false
where_single_line = false

match_arm_blocks = false
match_block_trailing_comma = true

use_field_init_shorthand = true
reorder_impl_items = true

overflow_delimited_expr = true
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true

# For recording
# max_width = 60
# chain_width = 40
# array_width = 40
